imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.xml }
    - { resource: hwi_oauth.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        gc_probability: 0
    fragments:       ~
    http_method_override: true
    translator: {fallback: ru}

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: blog
    document_managers:
        default:
            auto_mapping: true
            filters:
                softdeleteable:
                    class: Gedmo\SoftDeleteable\Filter\ODM\SoftDeleteableFilter
                    enabled: true

stof_doctrine_extensions:
    mongodb:
        default:
            sluggable: true
            timestampable: true
            softdeleteable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: UserBundle\Document\User
hautelook_alice:
    db_drivers:
        mongodb: ~      # Enable Doctrine ODM if is registered
    locale: ru_RU       # Locale to used for faker; must be a valid Faker locale otherwise will fallback to en_EN
    seed: 1             # A seed to make sure faker generates data consistently across runs, set to null to disable
    persist_once: false # Only persist objects once if multiple files are passed
    loading_limit: 5    # Maximum number of time the loader will try to load the files passed

# API
nelmio_api_doc: ~

fos_rest:
    body_converter:
        enabled: false  # Disable for comment form
    service:
        serializer: jms_serializer
    view:
        view_response_listener: force
        mime_types:
            json: ['application/json; charset=UTF-8', 'application/json'] #fix utf-8
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: ^/api, priorities: [json], fallback_format: 'json', prefer_extension: true }
            - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: false }

jms_serializer:
    visitors:
        json:
            options: [JSON_UNESCAPED_SLASHES, JSON_UNESCAPED_UNICODE]
