blog_api_v1_article_list:
    path: /article/list/{page}
    defaults: { _controller: BlogBundle:API\V1\Api:listArticles, page:1 }
    requirements:
        page: \d+
    methods: [GET]

blog_api_v1_article_view:
    path: /article/{slug}
    defaults: { _controller: BlogBundle:API\V1\Api:viewArticle }
    methods: [GET]
